### ISSUE TITLE
Neo Backup crashes when device is turned from portrait to landscape, but only when in an apps backup page.

### ISSUE THREAD

**Issue by Smutley** [NeoApplications/Neo-Backup#865]
**Description**
Neo Backup crashes when device is turned from portrait to landscape, but only when in an apps backup page. It does not crash when in the homepage. This occurs across 4 different devices running various Android OS'. It crashes on any device I have tried Neo Backup on. It usually gives no error or crash message, however, if one repeatedly causes it to crash by rotating from portrait to landscape it will give the "app keeps crashing" message eventually. See vid below.

**Steps To Reproduce**

1. Open Neo Backup and enter any app's backup page.
2. Rotate device from portrait to landscape.
3. Neo Backup instantly crashes and exits.

**Expected behavior**
Neo Backup should allow rotation of device to landscape mode while in any app's backup page.

**Screenshots**

https://github.com/NeoApplications/Neo-Backup/assets/122482571/a46c424d-44ab-45bb-85c5-88ee7cc3a548

**System Information(please complete the following information):**

- Device: Xiaomi Redmi Note 11;  Xiaomi Redmi Note 4; Pixel 8, Samsung A50
- Android Version: Note 11 = Evolution X 13, Note 4 = Lineage OS 13, Pixel 8 = Android 14, A50 = Evolution X 13
- ROM: (AOSP, MIUI, OOS...)   Note 11 = Evolution X 13, Note 4 = Lineage OS 13, Pixel 8 = Android 14, A50 = Evolution X 13
- App's Version: No Backup 8.3.6

-----------------------------

**Additional Notes**

* If you're on the latest Test version(from the TG-Channel or Matrix-Room) please report there directly, not here.

* If you're on the latest github version:
  
  * Please read the [FAQ](https://github.com/NeoApplications/Neo-Backup/blob/master/FAQ.md) first.
  * Please read all the open Issues. If one does match yours, leave a comment there if there's some extra information you can provide.

* If you're not on the latest github version. Update, then make sure that the bug is still there. If it's go further with reporting.

Thanks for reporting.

**Comment by machiav3lli** [comment]
I think this is already fixed either in my local builds or it's already pushed, I'll recheck when have some free time to wrap up the next point release.

**Comment by Smutley** [comment]
Neo Backup 8.3.8 no longer crashes when changed from portrait to landscape mode. However, the specific backup page one is in when changing from portrait to landscape still crashes, and cannot be accessed until one either opens another app's backup page, or exits and reopens Neo Backup.

**Comment by hg42** [comment]
I can confirm...

rotating appsheet from portrait to landscape didn't crash, but closes the appsheet.
Opening the appsheet again worked.
Rotating back to portrait with the opened appsheet worked, but the appsheet was closed.
Reopening it did not work, until I opened another appsheet, then the previous appsheet worked again.
I didn't investigate further, it might be that it depends on some condition.
Ok, I tried again with another app, started in landscape, appsheet, rotate, appsheet acannot be reopened, tried multiple times.
Opened another appsheet, then back to the previous, works.
Rotate, appsheet does not reopen.
So it does not seem to be dependent on landscape or portrait.
Only after the very first rotate the appsheet could be reopened, this might be the pattern until it's falsified.
